# Generated by Django 4.1.3 on 2022-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Artiklesss'},
        ),
        migrations.AddField(
            model_name='article',
            name='checking_name',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
