# Generated by Django 4.1.3 on 2022-12-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_delete_language_remove_article_checking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='default',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
